allowBuilds:
  esbuild: true
  lightningcss: true
  sharp: true
  workerd: true
onlyBuiltDependencies:
  - esbuild
  - lightningcss
  - sharp
  - workerd
catalog:
  "@cloudflare/vite-plugin": latest
  "@fontsource-variable/inter": latest
  "@fontsource-variable/space-grotesk": latest
  "@tailwindcss/typography": latest
  "@tailwindcss/vite": latest
  "@tanstack/devtools-vite": latest
  "@tanstack/react-devtools": latest
  "@tanstack/react-router": latest
  "@tanstack/react-router-devtools": latest
  "@tanstack/react-start": latest
  "@tanstack/router-cli": latest
  "@types/node": latest
  "@types/react": latest
  "@types/react-dom": latest
  "@vitejs/plugin-react": latest
  class-variance-authority: latest
  clsx: latest
  lucide-react: latest
  radix-ui: latest
  react: latest
  react-dom: latest
  shadcn: latest
  tailwind-merge: latest
  tailwindcss: latest
  tw-animate-css: latest
  typescript: latest
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  wrangler: latest
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
