/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 3d8717285f9a4d027a558ade743dd192)
interface __BaseEnv_Env {
  DB: D1Database;
  BETTER_AUTH_SECRET: string;
}
declare namespace Cloudflare {
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_SECRET">> {}
}
