/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c042ccb90a2e01d4165a65b38eac8401)
interface __BaseEnv_Env {
  VEO_SOUND_CONFIG: KVNamespace;
  DB: D1Database;
  BETTER_AUTH_SECRET: string;
  RESEND_API_KEY: string;
  SENTRY_DSN: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/server');
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, 'BETTER_AUTH_SECRET' | 'RESEND_API_KEY' | 'SENTRY_DSN'>
  > {}
}
