/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TeamsRouteRouteImport } from './routes/teams/route'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as TeamsTeamIdRouteRouteImport } from './routes/teams/$teamId/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SessionsJoinTokenRouteImport } from './routes/sessions/join.$token'
import { Route as TeamsTeamIdIndexRouteImport } from './routes/teams/$teamId/index'
import { Route as TeamsTeamIdBingoRulesRouteImport } from './routes/teams/$teamId/bingo-rules'
import { Route as TeamsTeamIdInvitationsRouteImport } from './routes/teams/$teamId/invitations'
import { Route as TeamsTeamIdLeaderboardRouteImport } from './routes/teams/$teamId/leaderboard'
import { Route as TeamsTeamIdMembersRouteImport } from './routes/teams/$teamId/members'
import { Route as TeamsTeamIdPlayRouteImport } from './routes/teams/$teamId/play'
import { Route as TeamsTeamIdTermsRouteImport } from './routes/teams/$teamId/terms'
import { Route as TeamsTeamIdSessionsSessionIdRouteImport } from './routes/teams/$teamId/sessions/$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRouteRoute = TeamsRouteRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamsRouteRoute,
} as any)
const TeamsTeamIdRouteRoute = TeamsTeamIdRouteRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => TeamsRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsJoinTokenRoute = SessionsJoinTokenRouteImport.update({
  id: '/sessions/join/$token',
  path: '/sessions/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdIndexRoute = TeamsTeamIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamsTeamIdRouteRoute,
} as any)
const TeamsTeamIdBingoRulesRoute = TeamsTeamIdBingoRulesRouteImport.update({
  id: '/bingo-rules',
  path: '/bingo-rules',
  getParentRoute: () => TeamsTeamIdRouteRoute,
} as any)
const TeamsTeamIdInvitationsRoute = TeamsTeamIdInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => TeamsTeamIdRouteRoute,
} as any)
const TeamsTeamIdLeaderboardRoute = TeamsTeamIdLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => TeamsTeamIdRouteRoute,
} as any)
const TeamsTeamIdMembersRoute = TeamsTeamIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => TeamsTeamIdRouteRoute,
} as any)
const TeamsTeamIdPlayRoute = TeamsTeamIdPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => TeamsTeamIdRouteRoute,
} as any)
const TeamsTeamIdTermsRoute = TeamsTeamIdTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => TeamsTeamIdRouteRoute,
} as any)
const TeamsTeamIdSessionsSessionIdRoute =
  TeamsTeamIdSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => TeamsTeamIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/teams': typeof TeamsRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/teams/$teamId': typeof TeamsTeamIdRouteRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/teams/': typeof TeamsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/sessions/join/$token': typeof SessionsJoinTokenRoute
  '/teams/$teamId/bingo-rules': typeof TeamsTeamIdBingoRulesRoute
  '/teams/$teamId/invitations': typeof TeamsTeamIdInvitationsRoute
  '/teams/$teamId/leaderboard': typeof TeamsTeamIdLeaderboardRoute
  '/teams/$teamId/members': typeof TeamsTeamIdMembersRoute
  '/teams/$teamId/play': typeof TeamsTeamIdPlayRoute
  '/teams/$teamId/terms': typeof TeamsTeamIdTermsRoute
  '/teams/$teamId/': typeof TeamsTeamIdIndexRoute
  '/teams/$teamId/sessions/$sessionId': typeof TeamsTeamIdSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/invite/$token': typeof InviteTokenRoute
  '/teams': typeof TeamsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/sessions/join/$token': typeof SessionsJoinTokenRoute
  '/teams/$teamId/bingo-rules': typeof TeamsTeamIdBingoRulesRoute
  '/teams/$teamId/invitations': typeof TeamsTeamIdInvitationsRoute
  '/teams/$teamId/leaderboard': typeof TeamsTeamIdLeaderboardRoute
  '/teams/$teamId/members': typeof TeamsTeamIdMembersRoute
  '/teams/$teamId/play': typeof TeamsTeamIdPlayRoute
  '/teams/$teamId/terms': typeof TeamsTeamIdTermsRoute
  '/teams/$teamId': typeof TeamsTeamIdIndexRoute
  '/teams/$teamId/sessions/$sessionId': typeof TeamsTeamIdSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/teams': typeof TeamsRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/teams/$teamId': typeof TeamsTeamIdRouteRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/teams/': typeof TeamsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/sessions/join/$token': typeof SessionsJoinTokenRoute
  '/teams/$teamId/bingo-rules': typeof TeamsTeamIdBingoRulesRoute
  '/teams/$teamId/invitations': typeof TeamsTeamIdInvitationsRoute
  '/teams/$teamId/leaderboard': typeof TeamsTeamIdLeaderboardRoute
  '/teams/$teamId/members': typeof TeamsTeamIdMembersRoute
  '/teams/$teamId/play': typeof TeamsTeamIdPlayRoute
  '/teams/$teamId/terms': typeof TeamsTeamIdTermsRoute
  '/teams/$teamId/': typeof TeamsTeamIdIndexRoute
  '/teams/$teamId/sessions/$sessionId': typeof TeamsTeamIdSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/teams'
    | '/account'
    | '/auth'
    | '/reset-password'
    | '/teams/$teamId'
    | '/invite/$token'
    | '/teams/'
    | '/api/auth/$'
    | '/sessions/join/$token'
    | '/teams/$teamId/bingo-rules'
    | '/teams/$teamId/invitations'
    | '/teams/$teamId/leaderboard'
    | '/teams/$teamId/members'
    | '/teams/$teamId/play'
    | '/teams/$teamId/terms'
    | '/teams/$teamId/'
    | '/teams/$teamId/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/reset-password'
    | '/invite/$token'
    | '/teams'
    | '/api/auth/$'
    | '/sessions/join/$token'
    | '/teams/$teamId/bingo-rules'
    | '/teams/$teamId/invitations'
    | '/teams/$teamId/leaderboard'
    | '/teams/$teamId/members'
    | '/teams/$teamId/play'
    | '/teams/$teamId/terms'
    | '/teams/$teamId'
    | '/teams/$teamId/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/teams'
    | '/account'
    | '/auth'
    | '/reset-password'
    | '/teams/$teamId'
    | '/invite/$token'
    | '/teams/'
    | '/api/auth/$'
    | '/sessions/join/$token'
    | '/teams/$teamId/bingo-rules'
    | '/teams/$teamId/invitations'
    | '/teams/$teamId/leaderboard'
    | '/teams/$teamId/members'
    | '/teams/$teamId/play'
    | '/teams/$teamId/terms'
    | '/teams/$teamId/'
    | '/teams/$teamId/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TeamsRouteRoute: typeof TeamsRouteRouteWithChildren
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  SessionsJoinTokenRoute: typeof SessionsJoinTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof TeamsRouteRoute
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteRouteImport
      parentRoute: typeof TeamsRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/join/$token': {
      id: '/sessions/join/$token'
      path: '/sessions/join/$token'
      fullPath: '/sessions/join/$token'
      preLoaderRoute: typeof SessionsJoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/': {
      id: '/teams/$teamId/'
      path: '/'
      fullPath: '/teams/$teamId/'
      preLoaderRoute: typeof TeamsTeamIdIndexRouteImport
      parentRoute: typeof TeamsTeamIdRouteRoute
    }
    '/teams/$teamId/bingo-rules': {
      id: '/teams/$teamId/bingo-rules'
      path: '/bingo-rules'
      fullPath: '/teams/$teamId/bingo-rules'
      preLoaderRoute: typeof TeamsTeamIdBingoRulesRouteImport
      parentRoute: typeof TeamsTeamIdRouteRoute
    }
    '/teams/$teamId/invitations': {
      id: '/teams/$teamId/invitations'
      path: '/invitations'
      fullPath: '/teams/$teamId/invitations'
      preLoaderRoute: typeof TeamsTeamIdInvitationsRouteImport
      parentRoute: typeof TeamsTeamIdRouteRoute
    }
    '/teams/$teamId/leaderboard': {
      id: '/teams/$teamId/leaderboard'
      path: '/leaderboard'
      fullPath: '/teams/$teamId/leaderboard'
      preLoaderRoute: typeof TeamsTeamIdLeaderboardRouteImport
      parentRoute: typeof TeamsTeamIdRouteRoute
    }
    '/teams/$teamId/members': {
      id: '/teams/$teamId/members'
      path: '/members'
      fullPath: '/teams/$teamId/members'
      preLoaderRoute: typeof TeamsTeamIdMembersRouteImport
      parentRoute: typeof TeamsTeamIdRouteRoute
    }
    '/teams/$teamId/play': {
      id: '/teams/$teamId/play'
      path: '/play'
      fullPath: '/teams/$teamId/play'
      preLoaderRoute: typeof TeamsTeamIdPlayRouteImport
      parentRoute: typeof TeamsTeamIdRouteRoute
    }
    '/teams/$teamId/terms': {
      id: '/teams/$teamId/terms'
      path: '/terms'
      fullPath: '/teams/$teamId/terms'
      preLoaderRoute: typeof TeamsTeamIdTermsRouteImport
      parentRoute: typeof TeamsTeamIdRouteRoute
    }
    '/teams/$teamId/sessions/$sessionId': {
      id: '/teams/$teamId/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/teams/$teamId/sessions/$sessionId'
      preLoaderRoute: typeof TeamsTeamIdSessionsSessionIdRouteImport
      parentRoute: typeof TeamsTeamIdRouteRoute
    }
  }
}

interface TeamsTeamIdRouteRouteChildren {
  TeamsTeamIdBingoRulesRoute: typeof TeamsTeamIdBingoRulesRoute
  TeamsTeamIdInvitationsRoute: typeof TeamsTeamIdInvitationsRoute
  TeamsTeamIdLeaderboardRoute: typeof TeamsTeamIdLeaderboardRoute
  TeamsTeamIdMembersRoute: typeof TeamsTeamIdMembersRoute
  TeamsTeamIdPlayRoute: typeof TeamsTeamIdPlayRoute
  TeamsTeamIdTermsRoute: typeof TeamsTeamIdTermsRoute
  TeamsTeamIdIndexRoute: typeof TeamsTeamIdIndexRoute
  TeamsTeamIdSessionsSessionIdRoute: typeof TeamsTeamIdSessionsSessionIdRoute
}

const TeamsTeamIdRouteRouteChildren: TeamsTeamIdRouteRouteChildren = {
  TeamsTeamIdBingoRulesRoute: TeamsTeamIdBingoRulesRoute,
  TeamsTeamIdInvitationsRoute: TeamsTeamIdInvitationsRoute,
  TeamsTeamIdLeaderboardRoute: TeamsTeamIdLeaderboardRoute,
  TeamsTeamIdMembersRoute: TeamsTeamIdMembersRoute,
  TeamsTeamIdPlayRoute: TeamsTeamIdPlayRoute,
  TeamsTeamIdTermsRoute: TeamsTeamIdTermsRoute,
  TeamsTeamIdIndexRoute: TeamsTeamIdIndexRoute,
  TeamsTeamIdSessionsSessionIdRoute: TeamsTeamIdSessionsSessionIdRoute,
}

const TeamsTeamIdRouteRouteWithChildren =
  TeamsTeamIdRouteRoute._addFileChildren(TeamsTeamIdRouteRouteChildren)

interface TeamsRouteRouteChildren {
  TeamsTeamIdRouteRoute: typeof TeamsTeamIdRouteRouteWithChildren
  TeamsIndexRoute: typeof TeamsIndexRoute
}

const TeamsRouteRouteChildren: TeamsRouteRouteChildren = {
  TeamsTeamIdRouteRoute: TeamsTeamIdRouteRouteWithChildren,
  TeamsIndexRoute: TeamsIndexRoute,
}

const TeamsRouteRouteWithChildren = TeamsRouteRoute._addFileChildren(
  TeamsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TeamsRouteRoute: TeamsRouteRouteWithChildren,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  SessionsJoinTokenRoute: SessionsJoinTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './app/router.tsx'
import type { startInstance } from './app/start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
